spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: stevo8519
    password: steveotheoneuser
  jpa:
    hibernate:
      ddl-auto: update  # Set your desired Hibernate DDL behavior
    show-sql: true  # Set to true for debugging, but false in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
